const lastUpdated = document.querySelector("#lastUpdated");
const languageButtons = document.querySelectorAll(".language-button");

const translations = {
  ja: {
    metaDescription: "日本での安定した生活、学習習慣、適応力を伝える個人ページ。",
    lifeMetaDescription: "生活と学習について記録するページ。",
    aiMetaDescription: "AI活用について記録するページ。",
    pageTitle: "個人ページ",
    lifePageTitle: "生活と学習",
    aiPageTitle: "AI活用",
    brandAria: "トップへ戻る",
    brand: "個人ページ",
    navAria: "ページ内ナビゲーション",
    navLearning: "生活・適応力・学習",
    navAi: "AI活用",
    navValues: "価値観",
    heroActionsAria: "主な操作",
    profileAria: "個人概要",
    heroTitle: "こんにちは。私は日本で誠実に生活し、学び続けています。",
    heroLifeTitle: "生活・適応力・学習",
    heroCopy:
      "このページは履歴書だけでは伝わりにくい、私の生活状況、学習習慣、適応力、長く安定して働きたい姿勢を補足するためのものです。",
    heroPrimary: "生活・適応力・学習を見る",
    heroAi: "AI活用を見る",
    heroAiTitle: "AI活用",
    heroAiCopy: "ChatGPTやCodexを使い、考えの整理、文章作成、画面設計、実装確認を少しずつ進めています。",
    nameLabel: "氏名",
    nameValue: "トウシュンヨウ",
    profileLabel: "現在の状態",
    profileKeywordsAria: "現在の状態の要点",
    profileKeyword1: "安定した生活",
    profileKeyword2: "継続的な学習",
    profileKeyword3: "長期的な成長",
    profileCopy:
      "企業の方に、履歴書だけでは見えにくい私の一面を知っていただきたいです。規則正しさ、責任感、日々の積み重ねを大切にしています。",
    factLocationLabel: "所在地",
    factLocationValue: "日本・熊本",
    factStatusLabel: "状態",
    factStatusValue: "熊本で安定して生活中",
    aboutTitle: "このページで伝えたいこと",
    aboutCard1Title: "誠実さ",
    aboutCard1Copy: "経験を大きく見せるのではなく、今の自分を正直に伝えます。安定して積み重ねられる部分を大切にしています。",
    aboutCard2Title: "安定性",
    aboutCard2Copy: "日本で生活する外国人として、規則正しい生活、丁寧なコミュニケーション、長期的な計画を重視しています。",
    aboutCard3Title: "成長",
    aboutCard3Copy: "言語、仕事への理解、基礎的なスキルを継続して学び、日々の小さな進歩を積み重ねています。",
    aiTitle: "AI活用について",
    aiLead: "このページは、AIを活用しながら作成した個人ページです。",
    aiBody1:
      "私はAIを単なる回答ツールではなく、自分の考えを整理し、学習を継続し、日々の課題を小さな仕組みに変えるためのパートナーとして活用しています。",
    aiBody2:
      "このWebページも、ChatGPTやCodexを使いながら、要件整理、文章作成、画面設計、実装、修正確認を行い、少しずつ形にしました。",
    learningTitle: "学習と成長の記録",
    lastUpdatedLoading: "最終更新：読み込み中",
    lastUpdatedFallback: "最終更新：更新中",
    lastUpdatedPrefix: "最終更新：",
    timeline1Time: "現在",
    timeline1Title: "個人ページの整理",
    timeline1Copy: "履歴書だけでは伝わりにくい情報を補足し、自分の生活状況や学習姿勢を分かりやすく伝えるために作成しました。",
    timeline2Time: "継続中",
    timeline2Title: "言語とコミュニケーション力の向上",
    timeline2Copy: "外国人として、言語とコミュニケーションの大切さを理解しています。表現、理解、職場でのやり取りを継続して練習しています。",
    timeline3Time: "長期",
    timeline3Title: "安定性と責任感を保つ",
    timeline3Copy: "日々の積み重ねを通して、信頼され、長く一緒に働ける人になることを目指しています。",
    valuesTitle: "大切にしていること",
    valuesAria: "価値観リスト",
    value1: "時間を守る",
    value2: "誠実",
    value3: "安定",
    value4: "継続学習",
    value5: "ルールを尊重",
    value6: "分かりやすいコミュニケーション",
    value7: "長期的な計画",
    value8: "責任感",
    updateTitle: "更新メモ",
    updateCopy1: "就職活動中は、このページを少しずつ更新していきます。",
    updateCopy2: "生活や学習の記録、AI活用の成果などを整理し、履歴書だけでは伝わりにくい部分を補足していきます。",
    footerLeft: "個人ページ",
    footerRight: "安定した生活、継続的な学習",
    backHome: "トップページへ戻る",
    lifeDetailTitle: "生活と学習の記録",
    lifeDetailCopy: "ここには、日々の生活、学習習慣、言語の練習、長く安定して働くために続けていることを書いていきます。",
    lifeStoryTitle: "これから書いていく内容",
    lifeBlock1Title: "生活の安定",
    lifeBlock1Copy: "熊本での生活リズム、健康管理、時間の使い方など、安定して働く土台になることを記録します。",
    lifeBlock2Title: "学習の継続",
    lifeBlock2Copy: "日本語、仕事への理解、基礎スキルなど、毎日少しずつ続けている学習を書いていきます。",
    lifeBlock3Title: "気づきと改善",
    lifeBlock3Copy: "生活や学習の中で気づいたこと、改善したこと、次に試したいことを整理します。",
    mediaImageLabel: "Image",
    mediaVideoLabel: "Video",
    mediaResultLabel: "Result",
    lifeMediaTitle: "写真で見る、学びと生活の工夫",
    lifeMediaLead: "日々の学習や生活の中で気づいたことを、写真と短い説明文で整理しています。",
    lifeMedia1Title: "学習メモやノート",
    lifeMedia1Copy: "日本語学習、生活の計画、気づいたことを画像で残します。",
    lifeMedia2Title: "短い記録動画",
    lifeMedia2Copy: "学習の流れや生活習慣を、短い動画で分かりやすく残します。",
    lifeMedia3Title: "改善したこと",
    lifeMedia3Copy: "続けた結果、変化したこと、次に試すことをまとめます。",
    aiDetailTitle: "AIをどう活用しているか",
    aiDetailCopy: "ここには、AIを使って考えを整理し、生活や学習を改善し、小さな成果につなげていく過程を書いていきます。",
    aiStoryTitle: "これから書いていく内容",
    aiBlock1Title: "考えの整理",
    aiBlock1Copy: "自分の考え、悩み、やることをAIと一緒に整理し、行動しやすい形にしています。",
    aiBlock2Title: "生活への活用",
    aiBlock2Copy: "予定、習慣、学習内容を小さく分け、続けやすい仕組みにするためにAIを使っています。",
    aiBlock3Title: "作った成果",
    aiBlock3Copy: "このWebページのように、要件整理、文章作成、画面設計、実装確認までAIと進めた成果を書いていきます。",
    aiMediaTitle: "AI活用の記録",
    aiMediaLead: "AIを使った過程や成果を、画像や短い動画と一緒に整理していきます。",
    aiMedia1Title: "考えを整理した記録",
    aiMedia1Copy: "AIと一緒に課題を分け、次の行動に変えた内容を画像で残します。",
    aiMedia2Title: "使い方の短い動画",
    aiMedia2Copy: "AIをどう使っているかを、短い録画で分かりやすく説明します。",
    aiMedia3Title: "作った成果",
    aiMedia3Copy: "Webページや文章など、AIと一緒に形にした成果をまとめます。",
  },
  zh: {
    metaDescription: "个人主页，展示在日本的稳定生活、学习习惯和适应能力。",
    lifeMetaDescription: "记录生活与学习的页面。",
    aiMetaDescription: "记录 AI 使用方式的页面。",
    pageTitle: "个人主页",
    lifePageTitle: "生活与学习",
    aiPageTitle: "AI 使用",
    brandAria: "返回顶部",
    brand: "个人主页",
    navAria: "页面导航",
    navLearning: "生活・适应力・学习",
    navAi: "AI 使用",
    navValues: "价值观",
    heroActionsAria: "主要操作",
    profileAria: "个人摘要",
    heroTitle: "你好，我在日本认真生活，也在持续学习。",
    heroLifeTitle: "生活・适应力・学习",
    heroCopy: "这个网页用来补充简历之外的信息：我的生活状态、学习习惯、适应能力和长期稳定发展的态度。",
    heroPrimary: "查看生活・适应力・学习",
    heroAi: "查看 AI 使用",
    heroAiTitle: "AI 使用",
    heroAiCopy: "我正在通过 ChatGPT 和 Codex，逐步完成想法整理、文案撰写、页面设计、实现和确认修改。",
    nameLabel: "姓名",
    nameValue: "董春阳",
    profileLabel: "当前状态",
    profileKeywordsAria: "当前状态要点",
    profileKeyword1: "稳定生活",
    profileKeyword2: "持续学习",
    profileKeyword3: "长期发展",
    profileCopy: "我希望通过这个页面，让企业看到简历之外更真实的一面：我重视规律、责任感和长期积累。",
    factLocationLabel: "所在地",
    factLocationValue: "日本・熊本",
    factStatusLabel: "状态",
    factStatusValue: "在熊本稳定生活中",
    aboutTitle: "这个网页想表达什么",
    aboutCard1Title: "真实",
    aboutCard1Copy: "不夸大经历，也不硬放没有完成的作品。页面只展示真实、稳定、可以长期积累的部分。",
    aboutCard2Title: "稳定",
    aboutCard2Copy: "作为在日本生活的外国人，我重视规律的生活节奏、可靠的沟通和长期计划。",
    aboutCard3Title: "成长",
    aboutCard3Copy: "我会持续学习语言、工作相关知识和基础技能，把每天的进步慢慢积累下来。",
    aiTitle: "关于 AI 的使用",
    aiLead: "这个页面是在使用 AI 协作的过程中逐步完成的个人主页。",
    aiBody1: "我不是把 AI 当成单纯的回答工具，而是把它作为整理想法、持续学习、把日常问题变成小型机制的协作伙伴。",
    aiBody2: "这个网页本身也通过 ChatGPT 和 Codex，完成了需求整理、文案撰写、页面设计、实现和修改确认。",
    learningTitle: "学习与成长记录",
    lastUpdatedLoading: "最近更新：正在读取",
    lastUpdatedFallback: "最近更新：持续更新中",
    lastUpdatedPrefix: "最近更新：",
    timeline1Time: "现在",
    timeline1Title: "整理个人主页",
    timeline1Copy: "用网页补充简历之外的信息，让别人更容易理解我的生活状态和学习态度。",
    timeline2Time: "持续",
    timeline2Title: "提升语言和沟通能力",
    timeline2Copy: "作为外国人，我知道语言和沟通很重要，所以会持续练习表达、理解和职场沟通。",
    timeline3Time: "长期",
    timeline3Title: "保持稳定和责任感",
    timeline3Copy: "希望通过日常积累，让自己成为一个可以被信任、可以长期合作的人。",
    valuesTitle: "我重视的事情",
    valuesAria: "价值观列表",
    value1: "守时",
    value2: "认真",
    value3: "稳定",
    value4: "持续学习",
    value5: "尊重规则",
    value6: "清楚沟通",
    value7: "长期计划",
    value8: "责任感",
    updateTitle: "更新记录",
    updateCopy1: "在求职期间，我会一点点持续更新这个页面。",
    updateCopy2: "我会整理生活、学习记录和 AI 使用成果，用来补充简历里不容易表达的部分。",
    footerLeft: "个人主页",
    footerRight: "稳定生活，持续学习",
    backHome: "返回首页",
    lifeDetailTitle: "生活与学习记录",
    lifeDetailCopy: "这里会用来写日常生活、学习习惯、语言练习，以及为了长期稳定工作而持续做的事情。",
    lifeStoryTitle: "之后会写的内容",
    lifeBlock1Title: "生活的稳定",
    lifeBlock1Copy: "记录在熊本的生活节奏、健康管理、时间使用等支撑稳定工作的基础。",
    lifeBlock2Title: "学习的持续",
    lifeBlock2Copy: "记录日语、工作理解、基础技能等每天一点点持续学习的内容。",
    lifeBlock3Title: "发现与改善",
    lifeBlock3Copy: "整理生活和学习中发现的问题、已经改善的地方，以及下一步想尝试的事情。",
    mediaImageLabel: "图片",
    mediaVideoLabel: "视频",
    mediaResultLabel: "成果",
    lifeMediaTitle: "用照片记录学习与生活中的方法",
    lifeMediaLead: "我会把日常学习和生活中发现的事情，用照片和简短说明整理出来。",
    lifeMedia1Title: "学习笔记和记录",
    lifeMedia1Copy: "用图片记录日语学习、生活计划和每天发现的小问题。",
    lifeMedia2Title: "短视频记录",
    lifeMedia2Copy: "用短视频展示学习流程或生活习惯，让内容更直观。",
    lifeMedia3Title: "改善过的事情",
    lifeMedia3Copy: "整理坚持之后发生的变化、已经改善的地方和下一步计划。",
    aiDetailTitle: "我是如何使用 AI 的",
    aiDetailCopy: "这里会写我如何用 AI 整理想法、改善生活和学习，并逐步做出小成果。",
    aiStoryTitle: "之后会写的内容",
    aiBlock1Title: "整理想法",
    aiBlock1Copy: "我会和 AI 一起整理自己的想法、烦恼和待办事项，让它们变成更容易行动的形式。",
    aiBlock2Title: "用于生活",
    aiBlock2Copy: "我用 AI 把计划、习惯和学习内容拆小，变成更容易持续的机制。",
    aiBlock3Title: "做出的成果",
    aiBlock3Copy: "例如这个网页，我会记录如何通过 AI 完成需求整理、文案、页面设计、实现和确认修改。",
    aiMediaTitle: "AI 使用记录",
    aiMediaLead: "这里会把使用 AI 的过程和成果，用图片或短视频一起整理出来。",
    aiMedia1Title: "整理想法的记录",
    aiMedia1Copy: "用图片记录我如何和 AI 一起拆分问题，并变成下一步行动。",
    aiMedia2Title: "使用方法短视频",
    aiMedia2Copy: "用短录屏说明我具体怎样使用 AI。",
    aiMedia3Title: "做出的成果",
    aiMedia3Copy: "整理网页、文章等通过 AI 协作完成的成果。",
  },
  en: {
    metaDescription: "A personal page showing stable life in Japan, learning habits, and adaptability.",
    lifeMetaDescription: "A page for recording life and learning.",
    aiMetaDescription: "A page for recording how I use AI.",
    pageTitle: "Personal Page",
    lifePageTitle: "Life and Learning",
    aiPageTitle: "AI Use",
    brandAria: "Back to top",
    brand: "Personal Page",
    navAria: "Page navigation",
    navLearning: "Life / Adaptability / Learning",
    navAi: "AI Use",
    navValues: "Values",
    heroActionsAria: "Main actions",
    profileAria: "Personal summary",
    heroTitle: "Hello, I live steadily in Japan and continue learning every day.",
    heroLifeTitle: "Life / Adaptability / Learning",
    heroCopy:
      "This page adds context beyond my resume: my life stability, learning habits, adaptability, and intention to grow steadily over the long term.",
    heroPrimary: "View life / adaptability / learning",
    heroAi: "View AI use",
    heroAiTitle: "AI Use",
    heroAiCopy: "I use ChatGPT and Codex to organize ideas, write copy, plan the interface, implement changes, and review results step by step.",
    nameLabel: "Name",
    nameValue: "Dong chunyang",
    profileLabel: "Current status",
    profileKeywordsAria: "Current status highlights",
    profileKeyword1: "Stable life",
    profileKeyword2: "Continuous learning",
    profileKeyword3: "Long-term growth",
    profileCopy:
      "I hope this page helps companies see the person behind the resume. I value routine, responsibility, and steady daily effort.",
    factLocationLabel: "Location",
    factLocationValue: "Kumamoto, Japan",
    factStatusLabel: "Status",
    factStatusValue: "Living steadily in Kumamoto",
    aboutTitle: "What this page is meant to show",
    aboutCard1Title: "Honesty",
    aboutCard1Copy: "I do not exaggerate my experience or pretend to have projects I have not completed. This page focuses on what is real, stable, and growing.",
    aboutCard2Title: "Stability",
    aboutCard2Copy: "As a foreign resident in Japan, I value a steady lifestyle, reliable communication, and long-term planning.",
    aboutCard3Title: "Growth",
    aboutCard3Copy: "I continue learning language, workplace understanding, and basic skills, building progress little by little.",
    aiTitle: "How I Use AI",
    aiLead: "This personal page was built step by step with AI as a working partner.",
    aiBody1:
      "I use AI not only as an answer tool, but as a partner for organizing my thoughts, continuing to learn, and turning daily challenges into small practical systems.",
    aiBody2:
      "This website itself was shaped with ChatGPT and Codex through requirement clarification, writing, interface planning, implementation, and review.",
    learningTitle: "Learning and Growth",
    lastUpdatedLoading: "Last updated: loading",
    lastUpdatedFallback: "Last updated: ongoing",
    lastUpdatedPrefix: "Last updated: ",
    timeline1Time: "Now",
    timeline1Title: "Organizing my personal page",
    timeline1Copy: "I created this page to add context beyond my resume and make my life situation and learning attitude easier to understand.",
    timeline2Time: "Ongoing",
    timeline2Title: "Improving language and communication",
    timeline2Copy: "As a foreign resident, I understand the importance of language and communication, so I keep practicing expression, comprehension, and workplace communication.",
    timeline3Time: "Long term",
    timeline3Title: "Keeping stability and responsibility",
    timeline3Copy: "Through daily effort, I aim to become someone who can be trusted and worked with over the long term.",
    valuesTitle: "Values I Care About",
    valuesAria: "Values list",
    value1: "Punctuality",
    value2: "Honesty",
    value3: "Stability",
    value4: "Continuous learning",
    value5: "Respect for rules",
    value6: "Clear communication",
    value7: "Long-term planning",
    value8: "Responsibility",
    updateTitle: "Update Memo",
    updateCopy1: "During my job search, I will keep updating this page little by little.",
    updateCopy2: "I will organize records of life, learning, and AI use to add context that is difficult to show through a resume alone.",
    footerLeft: "Personal Page",
    footerRight: "Stable life, continuous learning",
    backHome: "Back to top page",
    lifeDetailTitle: "Life and Learning Notes",
    lifeDetailCopy: "This page will hold notes about daily life, learning habits, language practice, and the steady effort behind long-term work.",
    lifeStoryTitle: "What I Will Add Here",
    lifeBlock1Title: "Stable Life",
    lifeBlock1Copy: "I will record my life rhythm in Kumamoto, health habits, time management, and the foundation for stable work.",
    lifeBlock2Title: "Continuous Learning",
    lifeBlock2Copy: "I will write about Japanese, workplace understanding, basic skills, and the learning I continue little by little.",
    lifeBlock3Title: "Noticing and Improving",
    lifeBlock3Copy: "I will organize what I notice in daily life and learning, what I improve, and what I want to try next.",
    mediaImageLabel: "Image",
    mediaVideoLabel: "Video",
    mediaResultLabel: "Result",
    lifeMediaTitle: "Learning and Life Ideas in Photos",
    lifeMediaLead: "I organize what I notice in daily learning and life with photos and short notes.",
    lifeMedia1Title: "Study Notes",
    lifeMedia1Copy: "I will use images to record Japanese study, life planning, and small things I notice.",
    lifeMedia2Title: "Short Videos",
    lifeMedia2Copy: "I will use short videos to show learning flow or daily habits clearly.",
    lifeMedia3Title: "Improvements",
    lifeMedia3Copy: "I will summarize what changed, what improved, and what I want to try next.",
    aiDetailTitle: "How I Use AI",
    aiDetailCopy: "This page will describe how I use AI to organize thoughts, improve life and learning, and turn small steps into outcomes.",
    aiStoryTitle: "What I Will Add Here",
    aiBlock1Title: "Organizing Thoughts",
    aiBlock1Copy: "I use AI to sort out my thoughts, concerns, and tasks so they become easier to act on.",
    aiBlock2Title: "Using AI in Daily Life",
    aiBlock2Copy: "I use AI to break plans, habits, and learning into smaller systems that are easier to continue.",
    aiBlock3Title: "Outcomes I Create",
    aiBlock3Copy: "For example, I will record how this website was shaped through requirements, writing, interface planning, implementation, and review.",
    aiMediaTitle: "AI Use Records",
    aiMediaLead: "I will organize the process and outcomes of using AI with images or short videos.",
    aiMedia1Title: "Organizing Thoughts",
    aiMedia1Copy: "I will use images to show how I break down problems with AI and turn them into next actions.",
    aiMedia2Title: "Short Usage Videos",
    aiMedia2Copy: "I will use short recordings to explain how I actually use AI.",
    aiMedia3Title: "Created Outcomes",
    aiMedia3Copy: "I will collect outcomes such as this website and writing shaped through AI collaboration.",
  },
};

let currentLanguage = localStorage.getItem("preferredLanguage") || "ja";

function t(key) {
  return translations[currentLanguage][key] || translations.ja[key] || "";
}

function updateLastModified() {
  if (!lastUpdated) {
    return;
  }

  const modified = new Date(document.lastModified);

  if (Number.isNaN(modified.getTime())) {
    lastUpdated.textContent = t("lastUpdatedFallback");
    return;
  }

  const locale = currentLanguage === "ja" ? "ja-JP" : currentLanguage === "zh" ? "zh-CN" : "en-US";
  lastUpdated.textContent = `${t("lastUpdatedPrefix")}${new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(modified)}`;
}

function applyLanguage(language) {
  currentLanguage = translations[language] ? language : "ja";
  localStorage.setItem("preferredLanguage", currentLanguage);
  document.documentElement.lang = currentLanguage === "zh" ? "zh-CN" : currentLanguage;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = t(element.dataset.i18n);
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((element) => {
    element.dataset.i18nAttr.split(",").forEach((pair) => {
      const [attribute, key] = pair.split(":");
      element.setAttribute(attribute.trim(), t(key.trim()));
    });
  });

  const titleElement = document.querySelector("title[data-i18n]");
  document.title = titleElement ? t(titleElement.dataset.i18n) : t("pageTitle");
  languageButtons.forEach((button) => {
    const isActive = button.dataset.lang === currentLanguage;
    button.classList.toggle("active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });
  updateLastModified();
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage(currentLanguage);
